before:
  hooks:
    - cp ../../LICENSE .
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    binary: devctl
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X 'main.version=' -X 'main.commit=' -X 'main.date=' -X 'main.goVersion=' 
      - ./usemsan=-msan
archives:
  - replacements:
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    format: tar.xz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  disable: true
changelog:
  skip: true
